version: '3'

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - /mnt/raid/nextcloud/db:/var/lib/postgresql/data
    env_file:
      - db.env
  
  redis:
    image: redis:alpine
    restart: always

  app:
    image: arm64v8/nextcloud:fpm-alpine
    restart: always
    dns:
      - 1.1.1.1
    links:
      - db
    volumes:
      - /mnt/raid/nextcloud/html:/var/www/html
    environment:
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    
  web:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:443
      - 82:80
    links:
      - app
    volumes:
      - /mnt/raid/nextcloud/html:/var/www/html:ro
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/cert:ro
    depends_on:
      - app
